name: Scanner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          sudo chmod +x scan
          sudo ./scan 1.0.0.0 255.255.255.255 scan.txt 1 1s
      - uses: actions/upload-artifact@v3
        with:
          name: scan
          path: scan.txt
